FROM nicholasjackson/consul-envoy

COPY config /config
COPY entrypoint.sh /usr/local/bin/entrypoint.sh

RUN apk add --no-cache gettext
RUN chmod +x /usr/local/bin/entrypoint.sh

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]