services:
# Consul Server
  consul-server:
    image: hashicorp/consul:latest
    container_name: consul-server
    command: "agent -server -bootstrap-expect=1 -ui -client=0.0.0.0"
    ports:
      - "8500:8500"
      - "8600:8600/udp"
      - "8300:8300"
      - "8301:8301"
      - "8301:8301/udp"
      - "8302:8302"
      - "8302:8302/udp"
    networks:
      - backend-network

# Evacuation service
  evacuation-service:
    build:
      context: ./services
      args:
        GIT_REPO: https://github.com/SafeMSA/evacuation.git
    container_name: evacuation
    depends_on:
      - rabbit-1
      - positioning-service
    networks:
      - backend-network

# Shelter service
  shelter-service:
    build: ./services/shelter
    container_name: shelter
    command: "agent -retry-join=consul-server -client=0.0.0.0"
    depends_on:
      - consul-server
    networks:
      - backend-network

# Positioning
  positioning-service:
    build:
      context: ./services
      args:
        GIT_REPO: https://github.com/SafeMSA/positioning.git
    container_name: positioning
    depends_on:
      - rabbit-1
    networks:
      - backend-network

  rabbit-1:
    build: ./rabbitmq
    hostname: rabbitmq1
    container_name: rabbitmq1
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_ERLANG_COOKIE=supersecretcookie
    volumes:
      - rabbitmq1-data:/var/lib/rabbitmq
      - rabbitmq1-logs:/var/log/rabbitmq
    networks:
      - data-network
      - backend-network

  rabbit-2:
    build: ./rabbitmq
    hostname: rabbitmq2
    container_name: rabbitmq2
    depends_on:
      - rabbit-1
    environment:
      - JOIN_CLUSTER_HOST=rabbitmq1
      - RABBITMQ_ERLANG_COOKIE=supersecretcookie
    volumes:
      - rabbitmq2-data:/var/lib/rabbitmq
      - rabbitmq2-logs:/var/log/rabbitmq
    networks:
      - data-network

  rabbit-3:
    build: ./rabbitmq
    hostname: rabbitmq3
    container_name: rabbitmq3
    depends_on:
      - rabbit-1
    environment:
      - JOIN_CLUSTER_HOST=rabbitmq1
      - RABBITMQ_ERLANG_COOKIE=supersecretcookie
    volumes:
      - rabbitmq3-data:/var/lib/rabbitmq
      - rabbitmq3-logs:/var/log/rabbitmq
    networks:
      - data-network

networks:
  backend-network:
    driver: bridge
  data-network:
    driver: bridge

volumes:
  rabbitmq1-data:
  rabbitmq1-logs:
  rabbitmq2-data:
  rabbitmq2-logs:
  rabbitmq3-data:
  rabbitmq3-logs: