services:
# Consul Server
  consul:
    image: consul:1.9.0
    command: ["consul","agent","-config-file=/config/consul-single-dc.hcl","-config-dir=/config"]
    volumes:
      - "./consul_config:/config"
    ports:
      - 8500:8500
    networks:
      network:
        ipv4_address: 10.5.255.2
    depends_on:
      - prometheus

  web:
    image: nicholasjackson/fake-service:v0.19.1
    environment:
      LISTEN_ADDR: 0.0.0.0:9091
      UPSTREAM_URIS: "http://localhost:9092"
      MESSAGE: "Hello World"
      NAME: "web"
      SERVER_TYPE: "http"
    ports:
    - "9091:9091"
    networks:
      network:
        ipv4_address: 10.5.255.10

  web-proxy:
    build:
      context: ./envoy
    restart: always
    environment:
      - SERVICE_TYPE=request
      - CONSUL_HTTP_ADDR=consul:8500
      - CONSUL_GRPC_ADDR=consul:8502
      - SERVICE_CONFIG=/config/config.hcl
      - SERVICE_NAME=web
      - SERVICE_ID=web
      - SERVICE_ADDRESS=10.5.255.10
    command: ["consul", "connect", "envoy","-sidecar-for", "web"]
    network_mode: "service:web"
    depends_on:
      - web
      - consul

# Evacuation service 1
  evac1:
    build:
      context: ./services
      args:
        GIT_REPO: https://github.com/SafeMSA/evacuation.git
    environment:
      - NAME=evac-1
    networks:
      network:
        ipv4_address: 10.5.255.3

  evac-proxy1:
    build:
      context: ./envoy
    restart: always
    environment:
      - SERVICE_TYPE=response
      - CONSUL_HTTP_ADDR=consul:8500
      - CONSUL_GRPC_ADDR=consul:8502
      - SERVICE_CONFIG=/config/config.hcl
      - SERVICE_NAME=evac
      - SERVICE_ID=evac1
      - SERVICE_ADDRESS=10.5.255.3
    command: ["consul", "connect", "envoy","-sidecar-for", "evac1"]
    network_mode: "service:evac1"
    depends_on:
      - evac1
      - web-proxy
      - consul

# Evacuation service 2
  evac2:
    build:
      context: ./services
      args:
        GIT_REPO: https://github.com/SafeMSA/evacuation.git
    environment:
      - NAME=evac-2
    networks:
      network:
        ipv4_address: 10.5.255.4

  evac-proxy2:
    build:
      context: ./envoy
    restart: always
    environment:
      - SERVICE_TYPE=response
      - CONSUL_HTTP_ADDR=consul:8500
      - CONSUL_GRPC_ADDR=consul:8502
      - SERVICE_CONFIG=/config/config.hcl
      - SERVICE_NAME=evac
      - SERVICE_ID=evac2
      - SERVICE_ADDRESS=10.5.255.4
    command: ["consul", "connect", "envoy","-sidecar-for", "evac2"]
    network_mode: "service:evac2"
    depends_on:
      - evac2
      - web-proxy
      - consul

# Positioning
  positioning-service:
    build:
      context: ./services
      args:
        GIT_REPO: https://github.com/SafeMSA/positioning.git
    container_name: positioning
    depends_on:
      - rabbit-1
    networks:
      - network

  rabbit-1:
    build: ./rabbitmq
    hostname: rabbitmq1
    container_name: rabbitmq1
    ports:
      - "5672:5672"    # AMQP
      - "15672:15672"  # Management UI
      - "15692:15692"  # Prometheus metrics
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_ERLANG_COOKIE=supersecretcookie
    volumes:
      - rabbitmq1-data:/var/lib/rabbitmq
      - rabbitmq1-logs:/var/log/rabbitmq
    networks:
      - network

  rabbit-2:
    build: ./rabbitmq
    hostname: rabbitmq2
    container_name: rabbitmq2
    depends_on:
      - rabbit-1
    environment:
      - JOIN_CLUSTER_HOST=rabbitmq1
      - RABBITMQ_ERLANG_COOKIE=supersecretcookie
    volumes:
      - rabbitmq2-data:/var/lib/rabbitmq
      - rabbitmq2-logs:/var/log/rabbitmq
    networks:
      - network

  rabbit-3:
    build: ./rabbitmq
    hostname: rabbitmq3
    container_name: rabbitmq3
    depends_on:
      - rabbit-1
    environment:
      - JOIN_CLUSTER_HOST=rabbitmq1
      - RABBITMQ_ERLANG_COOKIE=supersecretcookie
    volumes:
      - rabbitmq3-data:/var/lib/rabbitmq
      - rabbitmq3-logs:/var/log/rabbitmq
    networks:
      - network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      network:
        ipv4_address: 10.5.255.6

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml
    depends_on:
      - prometheus
    networks:
      - network

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16

volumes:
  rabbitmq1-data:
  rabbitmq1-logs:
  rabbitmq2-data:
  rabbitmq2-logs:
  rabbitmq3-data:
  rabbitmq3-logs:
  grafana-data: