services:
# Consul Server
  consul:
    container_name: consul
    image: consul:1.9.0
    command: ["consul","agent","-config-file=/config/consul-single-dc.hcl","-config-dir=/config"]
    volumes:
      - "./consul_config:/config"
    ports:
      - 8500:8500
    networks:
      network:
        ipv4_address: 10.5.255.2
    depends_on:
      - prometheus

  web:
    container_name: web
    build:
      context: ./services
      args:
        GIT_REPO: https://github.com/SafeMSA/web.git
    environment:
      NAME: "web"
    ports:
    - "9091:9091"
    networks:
      network:
        ipv4_address: 10.5.255.10

  web-proxy:
    container_name: web_proxy
    build:
      context: ./envoy
    restart: always
    environment:
      - CONSUL_HTTP_ADDR=consul:8500
      - CONSUL_GRPC_ADDR=consul:8502
      - SERVICE_TYPE=request
      - SERVICE_CONFIG=/config/config.hcl
      - SERVICE_NAME=web
      - SERVICE_ID=web
      - SERVICE_ADDRESS=10.5.255.10
      - SERVICE_PORT=9091
      - DESTINATION_NAME=evac
      - DESTINATION_PORT=9092
    command: ["consul", "connect", "envoy","-sidecar-for", "web"]
    network_mode: "service:web"
    depends_on:
      - web
      - consul

# Evacuation service 1
  evac1:
    container_name: evac1
    build:
      context: ./services
      args:
        GIT_REPO: https://github.com/SafeMSA/evacuation.git
    environment:
      - NAME=evac-1
    ports:
      - "9092:9092"
    networks:
      network:
        ipv4_address: 10.5.255.3

  evac-proxy1:
    container_name: evac-proxy1
    build:
      context: ./envoy
    restart: always
    environment:
      - CONSUL_HTTP_ADDR=consul:8500
      - CONSUL_GRPC_ADDR=consul:8502
      - SERVICE_TYPE=request
      - SERVICE_CONFIG=/config/config.hcl
      - SERVICE_NAME=evac
      - SERVICE_ID=evac1
      - SERVICE_ADDRESS=10.5.255.3
      - SERVICE_PORT=9092
      - DESTINATION_NAME=rabbitmq
      - DESTINATION_PORT=9093
    command: ["consul", "connect", "envoy","-sidecar-for", "evac1"]
    network_mode: "service:evac1"
    depends_on:
      - evac1
      - consul

# Evacuation service 2
  evac2:
    container_name: evac2
    build:
      context: ./services
      args:
        GIT_REPO: https://github.com/SafeMSA/evacuation.git
    environment:
      - NAME=evac-2
    ports:
      - "9098:9092"
    networks:
      network:
        ipv4_address: 10.5.255.4

  evac-proxy2:
    container_name: evac-proxy2
    build:
      context: ./envoy
    restart: always
    environment:
      - CONSUL_HTTP_ADDR=consul:8500
      - CONSUL_GRPC_ADDR=consul:8502
      - SERVICE_TYPE=request
      - SERVICE_CONFIG=/config/config.hcl
      - SERVICE_NAME=evac
      - SERVICE_ID=evac2
      - SERVICE_ADDRESS=10.5.255.4
      - SERVICE_PORT=9092
      - DESTINATION_NAME=rabbitmq
      - DESTINATION_PORT=9093
    command: ["consul", "connect", "envoy","-sidecar-for", "evac2"]
    network_mode: "service:evac2"
    depends_on:
      - evac2
      - consul

# Evacuation service 3
  evac3:
    container_name: evac3
    build:
      context: ./services
      args:
        GIT_REPO: https://github.com/SafeMSA/evacuation.git
    environment:
      - NAME=evac-3
    ports:
      - "9099:9092"
    networks:
      network:
        ipv4_address: 10.5.255.5

  evac-proxy3:
    container_name: evac-proxy3
    build:
      context: ./envoy
    restart: always
    environment:
      - CONSUL_HTTP_ADDR=consul:8500
      - CONSUL_GRPC_ADDR=consul:8502
      - SERVICE_TYPE=request
      - SERVICE_CONFIG=/config/config.hcl
      - SERVICE_NAME=evac
      - SERVICE_ID=evac3
      - SERVICE_ADDRESS=10.5.255.5
      - SERVICE_PORT=9092
      - DESTINATION_NAME=rabbitmq
      - DESTINATION_PORT=9093
    command: ["consul", "connect", "envoy","-sidecar-for", "evac3"]
    network_mode: "service:evac3"
    depends_on:
      - evac3
      - consul

  rabbit-1:
    build: ./rabbitmq
    hostname: rabbitmq1
    container_name: rabbitmq1
    ports:
      - "9093:9093"
      - "5672:5672"    # AMQP
      - "15672:15672"  # Management UI
      - "15692:15692"  # Prometheus metrics
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_ERLANG_COOKIE=supersecretcookie
    networks:
      network:
        ipv4_address: 10.5.255.100

  rabbit-proxy1:
    container_name: rabbit-proxy1
    build:
      context: ./envoy
    restart: always
    environment:
      - CONSUL_HTTP_ADDR=consul:8500
      - CONSUL_GRPC_ADDR=consul:8502
      - SERVICE_TYPE=request
      - SERVICE_CONFIG=/config/config.hcl
      - SERVICE_NAME=rabbitmq
      - SERVICE_ID=rabbitmq1
      - SERVICE_ADDRESS=10.5.255.100
      - SERVICE_PORT=5672
      - DESTINATION_NAME=rabbitmq
      - DESTINATION_PORT=9093
    command: ["consul", "connect", "envoy","-sidecar-for", "rabbitmq1"]
    network_mode: "service:rabbit-1"
    depends_on:
      - rabbit-1
      - consul

  rabbit-2:
    build: ./rabbitmq
    hostname: rabbitmq2
    container_name: rabbitmq2
    ports:
      - "9094:9093"
      - "5673:5672"    # AMQP
      - "15673:15672"  # Management UI
      - "15693:15692"  # Prometheus metrics
    depends_on:
      - rabbit-1
    environment:
      - JOIN_CLUSTER_HOST=rabbitmq1
      - RABBITMQ_ERLANG_COOKIE=supersecretcookie
    networks:
      network:
        ipv4_address: 10.5.255.101
  
  rabbit-proxy2:
    container_name: rabbit-proxy2
    build:
      context: ./envoy
    restart: always
    environment:
      - CONSUL_HTTP_ADDR=consul:8500
      - CONSUL_GRPC_ADDR=consul:8502
      - SERVICE_TYPE=response
      - SERVICE_CONFIG=/config/config.hcl
      - SERVICE_NAME=rabbitmq
      - SERVICE_ID=rabbitmq2
      - SERVICE_ADDRESS=10.5.255.101
      - SERVICE_PORT=5672
      - DESTINATION_NAME=rabbitmq
      - DESTINATION_PORT=9093
    command: ["consul", "connect", "envoy","-sidecar-for", "rabbitmq2"]
    network_mode: "service:rabbit-2"
    depends_on:
      - rabbit-2
      - consul

  rabbit-3:
    build: ./rabbitmq
    hostname: rabbitmq3
    container_name: rabbitmq3
    ports:
      - "9095:9093"
      - "5674:5672"    # AMQP
      - "15674:15672"  # Management UI
      - "15694:15692"  # Prometheus metrics
    depends_on:
      - rabbit-1
    environment:
      - JOIN_CLUSTER_HOST=rabbitmq1
      - RABBITMQ_ERLANG_COOKIE=supersecretcookie
    networks:
      network:
        ipv4_address: 10.5.255.102

  rabbit-proxy3:
    container_name: rabbit-proxy3
    build:
      context: ./envoy
    restart: always
    environment:
      - CONSUL_HTTP_ADDR=consul:8500
      - CONSUL_GRPC_ADDR=consul:8502
      - SERVICE_TYPE=response
      - SERVICE_CONFIG=/config/config.hcl
      - SERVICE_NAME=rabbitmq
      - SERVICE_ID=rabbitmq3
      - SERVICE_ADDRESS=10.5.255.102
      - SERVICE_PORT=5672
      - DESTINATION_NAME=rabbitmq
      - DESTINATION_PORT=9093
    command: ["consul", "connect", "envoy","-sidecar-for", "rabbitmq3"]
    network_mode: "service:rabbit-3"
    depends_on:
      - rabbit-3
      - consul

  tag1:
    build:
      context: ./services
      args:
        GIT_REPO: https://github.com/SafeMSA/tag.git
    networks:
      network:
        ipv4_address: 10.5.255.200

  tag-proxy1:
    container_name: tag-proxy1
    build:
      context: ./envoy
    restart: always
    environment:
      - CONSUL_HTTP_ADDR=consul:8500
      - CONSUL_GRPC_ADDR=consul:8502
      - SERVICE_TYPE=request
      - SERVICE_CONFIG=/config/config.hcl
      - SERVICE_NAME=tag
      - SERVICE_ID=tag1
      - SERVICE_ADDRESS=10.5.255.200
      - SERVICE_PORT=9092
      - DESTINATION_NAME=rabbitmq
      - DESTINATION_PORT=9093
    command: ["consul", "connect", "envoy","-sidecar-for", "tag1"]
    network_mode: "service:tag1"
    depends_on:
      - tag1
      - consul

  tag2:
    build:
      context: ./services
      args:
        GIT_REPO: https://github.com/SafeMSA/tag.git
    networks:
      network:
        ipv4_address: 10.5.255.201

  tag-proxy2:
    container_name: tag-proxy2
    build:
      context: ./envoy
    restart: always
    environment:
      - CONSUL_HTTP_ADDR=consul:8500
      - CONSUL_GRPC_ADDR=consul:8502
      - SERVICE_TYPE=request
      - SERVICE_CONFIG=/config/config.hcl
      - SERVICE_NAME=tag
      - SERVICE_ID=tag2
      - SERVICE_ADDRESS=10.5.255.201
      - SERVICE_PORT=9092
      - DESTINATION_NAME=rabbitmq
      - DESTINATION_PORT=9093
    command: ["consul", "connect", "envoy","-sidecar-for", "tag2"]
    network_mode: "service:tag2"
    depends_on:
      - tag2
      - consul

  tag3:
    build:
      context: ./services
      args:
        GIT_REPO: https://github.com/SafeMSA/tag.git
    networks:
      network:
        ipv4_address: 10.5.255.202

  tag-proxy3:
    container_name: tag-proxy3
    build:
      context: ./envoy
    restart: always
    environment:
      - CONSUL_HTTP_ADDR=consul:8500
      - CONSUL_GRPC_ADDR=consul:8502
      - SERVICE_TYPE=request
      - SERVICE_CONFIG=/config/config.hcl
      - SERVICE_NAME=tag
      - SERVICE_ID=tag3
      - SERVICE_ADDRESS=10.5.255.202
      - SERVICE_PORT=9092
      - DESTINATION_NAME=rabbitmq
      - DESTINATION_PORT=9093
    command: ["consul", "connect", "envoy","-sidecar-for", "tag3"]
    network_mode: "service:tag3"
    depends_on:
      - tag3
      - consul

  tag4:
    build:
      context: ./services
      args:
        GIT_REPO: https://github.com/SafeMSA/tag.git
    networks:
      network:
        ipv4_address: 10.5.255.203

  tag-proxy4:
    container_name: tag-proxy4
    build:
      context: ./envoy
    restart: always
    environment:
      - CONSUL_HTTP_ADDR=consul:8500
      - CONSUL_GRPC_ADDR=consul:8502
      - SERVICE_TYPE=request
      - SERVICE_CONFIG=/config/config.hcl
      - SERVICE_NAME=tag
      - SERVICE_ID=tag4
      - SERVICE_ADDRESS=10.5.255.203
      - SERVICE_PORT=9092
      - DESTINATION_NAME=rabbitmq
      - DESTINATION_PORT=9093
    command: ["consul", "connect", "envoy","-sidecar-for", "tag4"]
    network_mode: "service:tag4"
    depends_on:
      - tag4
      - consul

  tag5:
    build:
      context: ./services
      args:
        GIT_REPO: https://github.com/SafeMSA/tag.git
    networks:
      network:
        ipv4_address: 10.5.255.204

  tag-proxy5:
    container_name: tag-proxy5
    build:
      context: ./envoy
    restart: always
    environment:
      - CONSUL_HTTP_ADDR=consul:8500
      - CONSUL_GRPC_ADDR=consul:8502
      - SERVICE_TYPE=request
      - SERVICE_CONFIG=/config/config.hcl
      - SERVICE_NAME=tag
      - SERVICE_ID=tag5
      - SERVICE_ADDRESS=10.5.255.204
      - SERVICE_PORT=9092
      - DESTINATION_NAME=rabbitmq
      - DESTINATION_PORT=9093
    command: ["consul", "connect", "envoy","-sidecar-for", "tag5"]
    network_mode: "service:tag5"
    depends_on:
      - tag5
      - consul

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      network:
        ipv4_address: 10.5.255.6

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml
    depends_on:
      - prometheus
    networks:
      - network

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16

volumes:
  grafana-data: