global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq1:15692']
  - job_name: 'envoy'
    metrics_path: /metrics
    static_configs:
      - targets: ['evac:9102']
        labels:
          group: 'envoy'