# (Debian based)
FROM python:3.9-bookworm

RUN apt-get update && apt-get install -y git docker.io && rm -rf /var/lib/apt/lists/*
WORKDIR /app

ARG GIT_REPO
RUN git clone ${GIT_REPO} .

RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install requests
RUN pip install numpy

CMD ["sh", "-c", "git pull && python3 -u main.py"]