FROM rabbitmq:management

# Copy the entrypoint script to a known location
COPY entrypoint.sh /usr/local/bin/entrypoint.sh
COPY .erlang.cookie /var/lib/rabbitmq/.erlang.cookie

# Give execution permission to the script
RUN chmod +x /usr/local/bin/entrypoint.sh
RUN chmod 400 /var/lib/rabbitmq/.erlang.cookie

# Use absolute path in ENTRYPOINT
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
